from random import choice
priceLookup = {
        "toiletpaper": 40,
        "toothbrush": 40,
        "toothpaste": 40,
        "banana": 28,
        "milk": 23,
        "bread": 50,
        "hot dog": 50,
        "carrot cake": 60,
        "candy": 169,
        "chocolate pancake": 18,
        "chicken drumstick": 17,
        "cigar": 169,
        "fish burger": 300,
        "paprika": 70,
        "apple": 15,
        "orange": 20,
        "grapes": 35,
        "watermelon": 45,
        "pineapple": 50,
        "strawberries": 60,
        "blueberries": 70,
        "raspberries": 80,
        "blackberries": 90,
        "kiwi": 25,
        "mango": 30,
        "peach": 35,
        "plum": 40,
        "pear": 45,
        "nectarine": 50,
        "apricot": 55,
        "cherries": 60,
        "fig": 65,
        "pomegranate": 70,
        "avocado": 75,
        "lemon": 20,
        "lime": 25,
        "cucumber": 30,
        "tomato": 35,
        "lettuce": 40,
        "spinach": 45,
        "kale": 50,
        "broccoli": 55,
        "cauliflower": 60,
        "zucchini": 65,
        "eggplant": 70,
        "bell pepper": 75,
        "jalapeno": 80,
        "habanero": 85,
        "potato": 90,
        "sweet potato": 95,
        "onion": 100,
        "garlic": 105,
        "ginger": 110,
        "carrot": 115,
        "celery": 120,
        "radish": 125,
        "beet": 130,
        "turnip": 135,
        "parsnip": 140,
        "rutabaga": 145,
        "butternut squash": 150,
        "acorn squash": 155,
        "spaghetti squash": 160,
        "pumpkin": 165,
        "corn": 30,
        "peas": 25,
        "green beans": 35,
        "asparagus": 40,
        "brussels sprouts": 45,
        "artichoke": 50,
        "mushroom": 55,
        "cabbage": 20,
        "bok choy": 25,
        "collard greens": 30,
        "mustard greens": 35,
        "swiss chard": 40,
        "arugula": 45,
        "endive": 50,
        "radicchio": 55,
        "watercress": 60,
        "alfalfa sprouts": 20,
        "bean sprouts": 25,
        "snow peas": 30,
        "snap peas": 35,
        "okra": 40,
        "egg": 10,
        "cheese": 50,
        "yogurt": 20,
        "butter": 30,
        "cream": 25,
        "sour cream": 30,
        "cottage cheese": 35,
        "cream cheese": 40,
        "milkshake": 45,
        "ice cream": 50,
        "frozen yogurt": 55,
        "gelato": 60,
        "sorbet": 65,
        "popsicle": 10,
        "frozen pizza": 70,
        "frozen vegetables": 30,
        "frozen fruit": 35,
        "frozen dinners": 80,
        "frozen waffles": 25,
        "frozen pancakes": 20,
        "frozen french fries": 30,
        "frozen chicken nuggets": 40,
}

welcomeMessages = [
    "You walk trough the doors into the store and see cold flourescent roof lamps as far as your eyes can see.",
    "You step into the store, greeted by the hum of the air conditioning and the gleam of freshly polished floors.",
    "As you walk through the doors, the scent of freshly stocked produce fills the air, promising a productive day ahead.",
    "You enter the store, the soft buzz of fluorescent lights overhead guiding your way.",
    "The doors swing open, revealing aisles of neatly arranged products waiting to be discovered.",
    "You walk into the store, the familiar sight of well-organized shelves bringing a sense of calm and order.",
    "Stepping inside, you hear the gentle hum of the refrigeration units, a reminder of the day's tasks.",
    "You cross the threshold, the bright lights illuminating the path to a successful day.",
    "Entering the store, the cool air and the sight of fully stocked shelves greet you warmly.",
    "You walk through the doors, the sound of distant chatter and the rustle of shopping bags filling the space.",
    "As you step inside, the store's clean, crisp atmosphere welcomes you to a new day.",
    "You enter the store, the sight of colorful displays and the smell of fresh bread inviting you in.",
    "Walking through the doors, the store's organized chaos feels like a familiar friend.",
    "You step into the store, the bright lights and the hum of activity signaling the start of a new day.",
    "The doors open, revealing a world of possibilities within the neatly arranged aisles.",
    "You walk into the store, the cool air and the sight of well-stocked shelves setting the tone for the day.",
    "Entering the store, the soft glow of the lights and the quiet hum of the refrigeration units greet you.",
    "You step inside, the store's orderly rows and the scent of fresh produce welcoming you.",
    "As you walk through the doors, the store's bright lights and the promise of a productive day greet you.",
    "You enter the store, the sight of neatly arranged products and the hum of activity filling the space.",
    "Walking into the store, the cool air and the sight of fully stocked shelves bring a sense of calm."
]

randomWelcomeMessages = choice(welcomeMessages)

customerList = [
    
    "Ethan Brooks",
    "Ava Foster",
    "Liam Hayes",
    "Mia Sanders",
    "Noah Price",
    "Sophia Bennett",
    "Lucas Cooper",
    "Isabella Perry",
    "Mason Powell",
    "Amelia Jenkins",
    "James Russell",
    "Charlotte Griffin",
    "Benjamin Ward",
    "Harper Hughes",
    "Elijah Patterson",
    "Evelyn Howard",
    "Alexander Cox",
    "Abigail Richardson",
    "Henry Wood",
    "Ella Simmons",
    "Sebastian Foster",
    "Scarlett Bryant",
    "Jack Fisher",
    "Grace Henderson",
    "Aiden Coleman",
    "Chloe Graham",
    "Samuel Wallace",
    "Lily West",
    "David Jordan",
    "Hannah Reynolds",
    "Joseph Hamilton",
    "Aria Weaver",
    "Matthew Chapman",
    "Zoe Gardner",
    "Daniel Elliott",
    "Nora Lawson",
    "Michael Hart",
    "Luna Spencer",
    "William Bishop",
    "Layla Montgomery",
    "Logan Warren",
    "Riley Hunter",
    "Jackson Stone",
    "Victoria Black",
    "Levi Daniels",
    "Penelope Knight",
    "Owen Barrett",
    "Lillian Fox",
    "Ethan Hayes",
    "Ava Brooks",   
    "Abigail",
    "Alex",
    "Birdie",
    "Bouncer",
    "Caroline",
    "Clint",
    "Demetrius",
    "Dwarf",
    "Elliott",
    "Emily",
    "Evelyn",
    "George",
    "Gil",
    "Governor",
    "Grandpa",
    "Gus",
    "Haley",
    "Henchman",
    "Jas",
    "Jodi",
    "Kent",
    "Krobus",
    "Leo",
    "Lewis",
    "Linus",
    "Marlon",
    "Marnie",
    "Morris",
    "Mr. Qi",
    "Pam",
    "Penny",
    "Pierre",
    "Professor Snail",
    "Robin",
    "Sam",
    "Sandy",
    "Sebastian",
    "Shane",
    "Vincent",
    "Willy",
    "Wizard"

]

randomCustomer = choice(customerList)